services:
  dart-app:
    build: .
    image: dart-streamlit
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    privileged: true
    command: streamlit run src/main.py --server.address 0.0.0.0

  test:
    build: .
    volumes:
      - .:/app
    command: python3 src/test.py