version: "3"

services:
  dart-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dart-streamlit
    ports:
      - "8501:8501"
      - "5678:5678"
    volumes:
      - .:/app
      - app_data:/app/data
    privileged: true
    environment:
      - PYTHONBUFFERED=1
    command: python -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m streamlit run src/main.py

  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - app_data:/app/data
    command: ["/opt/venv/bin/python", "src/test.py"]
    privileged: true

volumes:
  app_data:
